//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWorkParametersStudentPairing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeWorkParametersStudentPairing()
        {
            this.PairingStudentPairings = new HashSet<PairingStudentPairing>();
        }
    
        public int PairingID { get; set; }
        public int ParametersID { get; set; }
        public int HomeWorkID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual HomeWork_Assign HomeWork_Assign { get; set; }
        public virtual HomeworkParameter HomeworkParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PairingStudentPairing> PairingStudentPairings { get; set; }
    }
}
