//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeWork
    {
        public int HomeWorkID { get; set; }
        public string Questions { get; set; }
        public string Answers { get; set; }
        public Nullable<int> IsCorrect { get; set; }
        public Nullable<decimal> Percentage_Correct { get; set; }
        public int SubSyllabusID { get; set; }
        public int ID { get; set; }
        public string StudentAnswers { get; set; }
    
        public virtual HomeWork_Assign HomeWork_Assign { get; set; }
        public virtual SubSyllabu SubSyllabu { get; set; }
    }
}
