//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeworkParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeworkParameter()
        {
            this.HomeWorkParametersStudentPairings = new HashSet<HomeWorkParametersStudentPairing>();
        }
    
        public int ParametersID { get; set; }
        public Nullable<int> NoOfTerms { get; set; }
        public Nullable<int> NoOfLawsInUse { get; set; }
        public Nullable<decimal> HighestNumber { get; set; }
        public Nullable<int> HighestNumberPow { get; set; }
        public Nullable<int> ComplexityID { get; set; }
        public Nullable<int> ArithOrGeom { get; set; }
        public Nullable<decimal> highest_a { get; set; }
        public Nullable<int> highest_n { get; set; }
        public Nullable<decimal> highest_d { get; set; }
        public Nullable<decimal> highest_r { get; set; }
        public Nullable<int> DegreeOfRemoval { get; set; }
        public Nullable<int> maxSides { get; set; }
        public Nullable<int> AngleOrSide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWorkParametersStudentPairing> HomeWorkParametersStudentPairings { get; set; }
    }
}
