//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolBookEntities : DbContext
    {
        public SchoolBookEntities()
            : base("name=SchoolBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GradeSyllabusPairing> GradeSyllabusPairings { get; set; }
        public virtual DbSet<HomeWork> HomeWork { get; set; }
        public virtual DbSet<HomeWork_Assign> HomeWork_Assign { get; set; }
        public virtual DbSet<HomeworkParameter> HomeworkParameters { get; set; }
        public virtual DbSet<HomeWorkParametersStudentPairing> HomeWorkParametersStudentPairings { get; set; }
        public virtual DbSet<PairingStudentPairing> PairingStudentPairings { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<SubSyllabu> SubSyllabus { get; set; }
        public virtual DbSet<Syllabu> Syllabus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TutorStudentRelationship> TutorStudentRelationships { get; set; }
        public virtual DbSet<TutorTable> TutorTables { get; set; }
        public virtual DbSet<YouTubeSpecific> YouTubeSpecifics { get; set; }
    }
}
