//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.PairingStudentPairings = new HashSet<PairingStudentPairing>();
            this.TutorStudentRelationships = new HashSet<TutorStudentRelationship>();
        }
    
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<int> AreaCode { get; set; }
        public string EmailAddress { get; set; }
        public string PlaceKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PairingStudentPairing> PairingStudentPairings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorStudentRelationship> TutorStudentRelationships { get; set; }
    }
}
