//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSyllabu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubSyllabu()
        {
            this.HomeWork = new HashSet<HomeWork>();
            this.HomeWork_Assign = new HashSet<HomeWork_Assign>();
            this.YouTubeSpecifics = new HashSet<YouTubeSpecific>();
        }
    
        public int ID { get; set; }
        public int SyllabusID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWork> HomeWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeWork_Assign> HomeWork_Assign { get; set; }
        public virtual Syllabu Syllabu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YouTubeSpecific> YouTubeSpecifics { get; set; }
    }
}
