//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolBook.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorStudentRelationship
    {
        public int ID { get; set; }
        public int TutorID { get; set; }
        public int StudentID { get; set; }
    
        public virtual StudentTable StudentTable { get; set; }
        public virtual TutorTable TutorTable { get; set; }
    }
}
